//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piss.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_ItemType_ItemTypeDetail_Assoc
    {
        public int ItemId { get; set; }
        public int ItemTypeId { get; set; }
        public int ItemTypeDetailId { get; set; }
        public string Value { get; set; }
    }
}
