//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piss.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemType()
        {
            this.ItemTypeDetails = new HashSet<ItemTypeDetail>();
        }
    
        public long ItemTypeId { get; set; }
        public string Description { get; set; }
        public Nullable<int> ImageId { get; set; }
        public bool IsBorrowed { get; set; }
        public bool IsActive { get; set; }
        public string UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemTypeDetail> ItemTypeDetails { get; set; }
    }
}
