//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piss.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public long ItemId { get; set; }
        public long ItemTypeId { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UserId { get; set; }
        public bool IsActive { get; set; }
        public bool IsBorrowed { get; set; }
        public Nullable<int> ImageId { get; set; }
    
        public virtual ItemType ItemType { get; set; }
    }
}
