//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piss.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public long ItemID { get; set; }
        public int ItemType { get; set; }
        public string Description { get; set; }
        public Nullable<int> ImageID { get; set; }
        public bool IsBorrowed { get; set; }
        public bool IsActive { get; set; }
    }
}
